### ISSUE TITLE
More about filterCoos and filterJDS

### ISSUE THREAD

**Issue by robyww** [cds-astro/cds-moc-rust#2]
Can you tell me more about what this function does? I am not following what the inputs and output are.

>  Filter operations (return arrays containing with 0 (out of the MOC) or 1 (in the MOC))
filterCoos(name, coos_deg: Float64Array) -> Uint8Array

I think it is filtering by coordinates. However, I expect to enter ra/dec so how it that specified.

**Comment by fxpineau** [comment]
@robyww the README only contains an overview of available functions (I just fixed the wording, to be pushed).
For a better documentation, you may have a look at the `moc.js` file in the [MOCWasm release](https://github.com/cds-astro/cds-moc-rust/releases/download/v0.4.0/moc-wasm-v0.4.0.tar.gz). You will e.g. find:
```
/**
* Returns an array of boolean (u8 set to 1 or 0) telling if the pairs of coordinates
* in the input array are in (true=1) or out of (false=0) the S-MOC of given name.
* # Params
* * `name`: the name of the S-MOC to be used for filtering
* * `coos_deg`: list of coordinates in degrees `[lon_1, lat_1, lon_2, lat_2, ..., lon_n, lat_n]`
* # Remarks
* The size of the returned boolean (u8) array his half the size of the input array
* (since the later contains pairs of coordinates).
* @param {string} name
* @param {Float64Array} coos_deg
* @returns {Uint8Array}
*/
export function filterCoos(name, coos_deg) {
   ...
}
```
which comes from [this part of the source code](https://github.com/cds-astro/cds-moc-rust/blob/main/crates/wasm/src/lib.rs?#L1249-L1258).

Let me know if you think it is more convenient to take in input one array of lon and one array of lat instead of an array mixing lon and lat (or something else).

I am considering generating the doc with [JSDoc](https://github.com/jsdoc/jsdoc).

**Comment by robyww** [comment]
That very helpful, thank you. I had downloaded it but not looked at moc.js closely. It you don't make JSDocs you probably should make reference to where the documentation is. Maybe you already have and I missed it.

Also - I just wanted to let you know that this is one of the most interesting things to come out of the IVOA Interop this week. I expect we will incorporate it into[ Firefly](https://github.com/Caltech-IPAC/firefly) at some point in the next 12 months. This library give us the opportunity to implement many more MOC features.  

Thanks for building it.
